version: "3"

services:
    app:
        build: .
        volumes:
            - ".:/app"
        ports:
            - "3000:3000"
        depends_on:
            - db
    db:
        image: postgres:11.3
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
